services:

  api:
    image: squareapi
    build:
      dockerfile: Dockerfile.api
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DB_SQUARETRACK_URL}
      PORT: ${API_PORT_INT}
    env_file:
      - path: .env
        required: true
    volumes:
      - ./api:/app/
    networks:
    #   - backend
      - default
      - squarenet
    ports:
      #- ${API_PORT}:${API_PORT}
      - ${API_PORT_EXT}:${API_PORT_INT}
    container_name: square.api
    command: npm run dev
    # command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PW}
      PGPORT: ${DB_PORT_INT}
    command: -p ${DB_PORT_INT}
    ports:
      - "${DB_PORT_EXT}:${DB_PORT_INT}"
    container_name: square.db
    volumes:
      - squaredb_vol:/var/lib/postgresql/data
    networks:
      - default
      - squarenet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u ${DB_POSTGRES_USER} -d ${DB_POSTGRES_NAME} -p ${DB_PORT_INT}"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 30s

  fe:
    image: squarefe
    build:
      dockerfile: Dockerfile.fe
    environment:
      NODE_ENV: development,
      PORT: ${FE_PORT_INT}
    env_file:
      - path: .env
        required: true
    volumes:
      - ./fe/public:/app/public
      - ./fe/src:/app/src
    networks:
      - default
      - squarenet
    ports:
      - ${FE_PORT_EXT}:${FE_PORT_INT}
    container_name: square.fe
    command: npm run dev
    # command: npm run dev
    depends_on:
      - api
      - db

  studio:
    image: squareapi
    build:
      dockerfile: Dockerfile.api
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DB_SQUARETRACK_URL}
    env_file:
      - path: .env
        required: true
    volumes:
      - ./api:/app/
    networks:
    #   - backend
      - default
      - squarenet
    ports:
      - ${STUDIO_PORT_EXT}:${STUDIO_PORT_INT}
    container_name: square.studio
    command: npx prisma studio -p ${STUDIO_PORT_INT}
    # command: npm run dev
    depends_on:
      - db
      - api

networks:
  squarenet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.17.0.0/24
  default:
    driver: bridge
    external: false

volumes:
  squaredb_vol:

