
FROM node:22-alpine3.19

RUN mkdir /app
WORKDIR /app

COPY api/package.json api/package-lock.json api/tsconfig.json api/src ./

RUN npm install

# RUN npx prisma generate --schema=./src/model

CMD ["npm", "run", "dev"]
