services:
  
  
  db:
    image: postgres:latest
    restart: always
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PW}
      PGPORT: ${DB_PORT}
    command: -p ${DB_PORT}
    ports:
      - "${DB_PORT}:5432"
    container_name: square.db
    volumes:
      - squaredb_vol:/var/lib/postgresql/data
    networks:
      - default
      - squarenet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u ${DB_POSTGRES_USER} -d ${DB_POSTGRES_NAME} -p 5432"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 30s

  # dbadmin:
  #   profiles:
  #     - admin,
  #   image: dpage/pgadmin4:latest
  #   env_file:
  #     - .env
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: {$PGADMIN_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
  #     PGADMIN_DISABLE_POSTFIX: true
  #     PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
  #   ports:
  #     - "${PGADMIN_PORT}:5433"
  #   depends_on:
  #     - db

networks:
  squarenet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.17.0.0/24
  default:
    driver: bridge
    external: false

volumes:
  squaredb_vol:

